spring:
  config:
    activate:
      on-profile: blog-search
blog:
  search:
    kakao:
      url: "https://dapi.kakao.com/v2/search/blog"
      api-key: ENC(QGNGgE95fLShD8Clseeuv5yaX5fQ0oNDcnb1w9U0Nlnkp7Nf4ffTOe6bXMIOhsgD)